### ISSUE TITLE
data

### ISSUE THREAD

**Issue by breznak** [breznak/ML.benchmark#18]
- [ ] eval on clean data: RDSE, Scalar, Adaptive = choose 1 for other anomaly -> https://github.com/breznak/ML.benchmark/issues/19
- [ ] eval boosting on/off! -> https://github.com/breznak/ML.benchmark/issues/24
- [ ] noise + add higher noise https://github.com/breznak/ML.benchmark/issues/25
- [ ] dataLoss - make extreme (random) changes https://github.com/breznak/ML.benchmark/issues/23
- [ ] gauss 2 - "make fatter" 1 sine hill #26
- [ ] new cat: LowHZ - sine modulated eith sigmoid (sigmoid is "main") #27
- [ ] point a. - phase = add trial with smaller (+-10%, not 1PI) phase shift #28
- [ ] doc usage for dev/experimentator #32
- [ ] correlated anomaly (2 signal) #29
- [ ] 500signal,500noise,repeat #30

**Comment by breznak** [comment]
@wattik created separate issues, so we'll see what we've really done :stuck_out_tongue_winking_eye: 
Closing here. 
We should finish the Open milestone ASAP
